// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    FlugPlus: typeof import('./src/components/FlugPlus.vue')['default']
    SearchEngine: typeof import('./src/components/SearchEngine.vue')['default']
    SolarPlus: typeof import('./src/components/SolarPlus.vue')['default']
  }
}

export { }
