[build.environment]
  NETLIFY_USE_YARN = "true"

[[redirects]]
	status = 200
  from = "/api/*"
  to = "/.netlify/functions/:splat"

[[redirects]]
	from = "/*"
	to = "/index.html"
	status = 200

[functions]
  directory = "src/api"