[build]
	publish = "dist/"
	command = "yarn build"

[build.environment]
  NETLIFY_USE_YARN = "true"

[[redirects]]
	from = "/smash/*"
	to = "/smash/index.html"
	status = 200
	force = true

[[redirects]]
	from = "/"
	to = "/smash/"
	status = 301
	force = true