[build]
	publish = "dist/"
	command = "yarn build"

[build.environment]
  NETLIFY_USE_YARN = "true"

[[redirects]]
	from = "/"
	to = "/smash/"
	status = 301

[[redirects]]
	from = "/smash/*"
	to = "/smash/:splat"
	status = 301